/**
 * 阿里巴巴 Java 开发手册规约数据 —— 黄山版（最新版 2022.8）
 *
 * 数据来源：《阿里巴巴 Java 开发手册（黄山版）》
 * 版本 1.7.1 → 黄山版相较嵩山版新增：
 *   - 日期时间处理专节
 *   - 前后端协作规约
 *   - 应用性能规约
 *   - 研发效能
 *   - Spring 工程结构增强
 *
 * 分十一大维度：编程规约 / 异常日志 / 单元测试 / 安全规约 / MySQL 数据库 /
 *             工程结构 / 设计规约 / 前后端规约 / 日期时间 / 应用性能 / 研发效能
 * 级别：MANDATORY（强制）/ RECOMMENDED（推荐）/ REFERENCE（参考）
 */

export interface Rule {
  code: string
  title: string
  level: 'MANDATORY' | 'RECOMMENDED' | 'REFERENCE'
  category: string
  content: string
  exampleBad?: string
  exampleGood?: string
}

export const rules: Rule[] = [
  // ============ 一、编程规约 - (一) 命名规约 ============
  { code: '1.1.1', level: 'MANDATORY', category: '编程规约-命名',
    title: '命名不能以下划线或美元符号开始/结束',
    content: '代码中的命名均不能以下划线或美元符号开始，也不能以下划线或美元符号结束。',
    exampleBad: '_name / __name / $Object / name_ / name$ / Object$',
    exampleGood: 'name / object' },
  { code: '1.1.2', level: 'MANDATORY', category: '编程规约-命名',
    title: '禁止使用拼音与英文混合，更不允许直接使用中文',
    content: '代码中的命名严禁使用拼音与英文混合的方式，更不允许直接使用中文的方式。正确的英文拼写和语法可以让阅读者易于理解，避免歧义。',
    exampleBad: 'DaZhePromotion[打折] / getPingfenByName()[评分] / int 某变量 = 3',
    exampleGood: 'discountPromotion / getRatingByName() / int someVar = 3' },
  { code: '1.1.3', level: 'MANDATORY', category: '编程规约-命名',
    title: '类名使用 UpperCamelCase 风格',
    content: '类名使用 UpperCamelCase 风格，必须遵从驼峰形式，但以下情形例外：DO / BO / DTO / VO / AO / PO / UID 等。',
    exampleBad: 'macroPolo / UserDo / XMLService / TCPUDPDeal / TAPromotion',
    exampleGood: 'MarcoPolo / UserDO / XmlService / TcpUdpDeal / TaPromotion' },
  { code: '1.1.4', level: 'MANDATORY', category: '编程规约-命名',
    title: '方法/参数/成员/局部变量使用 lowerCamelCase',
    content: '方法名、参数名、成员变量、局部变量都统一使用 lowerCamelCase 风格，必须遵从驼峰形式。',
    exampleGood: 'localValue / getHttpMessage() / inputUserId' },
  { code: '1.1.5', level: 'MANDATORY', category: '编程规约-命名',
    title: '常量命名全部大写 + 下划线分隔',
    content: '常量命名全部大写，单词间用下划线隔开，力求语义表达完整清楚，不要嫌名字长。',
    exampleBad: 'MAX_COUNT',
    exampleGood: 'MAX_STOCK_COUNT' },
  { code: '1.1.6', level: 'MANDATORY', category: '编程规约-命名',
    title: '抽象类/异常/测试类命名约定',
    content: '抽象类命名使用 Abstract 或 Base 开头；异常类命名使用 Exception 结尾；测试类命名以它要测试的类的名称开始，以 Test 结尾。',
    exampleGood: 'AbstractUserService / BaseController / UserException / UserServiceTest' },
  { code: '1.1.7', level: 'MANDATORY', category: '编程规约-命名',
    title: '中括号是数组类型的一部分',
    content: '类型与中括号紧挨相连来定义数组。',
    exampleBad: 'String args[];',
    exampleGood: 'String[] args;' },
  { code: '1.1.8', level: 'MANDATORY', category: '编程规约-命名',
    title: 'POJO 布尔属性不加 is 前缀',
    content: 'POJO 类中布尔类型变量不要加 is 前缀，否则部分框架解析会引起序列化错误。',
    exampleBad: 'Boolean isDeleted; // getter 会是 isDeleted() 而非 getIsDeleted()',
    exampleGood: 'Boolean deleted;' },
  { code: '1.1.9', level: 'MANDATORY', category: '编程规约-命名',
    title: '包名统一小写',
    content: '包名统一使用小写，点分隔符之间有且仅有一个自然语义的英语单词。包名统一使用单数形式。',
    exampleGood: 'com.alibaba.open.util' },
  { code: '1.1.10', level: 'MANDATORY', category: '编程规约-命名',
    title: '杜绝完全不规范的缩写',
    content: '避免望文不知义。任何自定义编程元素在命名时使用尽量完整的单词组合来表达其意。',
    exampleBad: 'AbsClass / condi',
    exampleGood: 'AbstractClass / condition' },
  { code: '1.1.11', level: 'RECOMMENDED', category: '编程规约-命名',
    title: '接口不加 I 前缀；实现类用 Impl 后缀',
    content: 'Service / DAO 类暴露给外部的方法一律是接口，内部的实现类用 Impl 的后缀与接口区别。',
    exampleBad: 'class IUserService / UserServiceImpl',
    exampleGood: 'interface UserService / class UserServiceImpl' },
  { code: '1.1.12', level: 'REFERENCE', category: '编程规约-命名',
    title: '枚举类名用 Enum 结尾、成员大写',
    content: '枚举类名带上 Enum 后缀，枚举成员名称需要全大写，单词间用下划线隔开。',
    exampleGood: 'ProcessStatusEnum { SUCCESS, UNKNOWN_REASON }' },
  { code: '1.1.13', level: 'REFERENCE', category: '编程规约-命名',
    title: '各层方法命名约定',
    content: '获取单个对象用 get 前缀；获取多个用 list 前缀；获取统计值用 count 前缀；插入方法用 save/insert 前缀；删除方法用 remove/delete 前缀；修改方法用 update 前缀。',
    exampleGood: 'getUserById / listByStatus / countByDay / saveOrder / removeById / updateStatus' },
  { code: '1.1.14', level: 'REFERENCE', category: '编程规约-命名',
    title: '领域模型命名约定',
    content: '数据对象 xxxDO（对应数据库表名）；数据传输对象 xxxDTO；展示对象 xxxVO；POJO 是对 DO/DTO/BO/VO 的统称，不要定义 xxxPOJO。' },

  // ============ 一、编程规约 - (二) 常量定义 ============
  { code: '1.2.1', level: 'MANDATORY', category: '编程规约-常量',
    title: '不允许任何魔法值出现在代码中',
    content: '不允许任何"魔法值"（即未经预先定义的常量）直接出现在代码中。',
    exampleBad: 'String key = "Id#taobao_" + tradeId;',
    exampleGood: 'static final String KEY_PREFIX = "Id#taobao_";\nString key = KEY_PREFIX + tradeId;' },
  { code: '1.2.2', level: 'MANDATORY', category: '编程规约-常量',
    title: 'long 字面量用大写 L',
    content: 'long 或 Long 初始赋值时必须使用大写的 L，不能是小写的 l。小写容易跟数字 1 混淆。',
    exampleBad: 'Long a = 2l; // 看着像 21 而非 Long 型的 2',
    exampleGood: 'Long a = 2L;' },
  { code: '1.2.3', level: 'RECOMMENDED', category: '编程规约-常量',
    title: '不要一个常量类维护所有常量',
    content: '应按常量功能进行归类分开维护，如缓存常量放 CacheConsts，配置相关常量放 ConfigConsts。' },
  { code: '1.2.4', level: 'RECOMMENDED', category: '编程规约-常量',
    title: '常量复用层次',
    content: '如果变量值仅在一个固定范围内变化用 enum 类型来定义。如果还带有名称之外的延伸属性，必须使用 enum 类型。',
    exampleGood: 'enum SeasonEnum { SPRING(1), SUMMER(2), AUTUMN(3), WINTER(4); ... }' },

  // ============ 一、编程规约 - (三) 代码格式 ============
  { code: '1.3.1', level: 'MANDATORY', category: '编程规约-格式',
    title: '大括号使用约定',
    content: '如果大括号内为空，则简洁地写成{}即可，不需要换行；如果是非空代码块，则：左大括号前不换行、左大括号后换行、右大括号前换行、右大括号后还有 else 等代码则不换行。' },
  { code: '1.3.2', level: 'MANDATORY', category: '编程规约-格式',
    title: '左小括号和字符之间不出现空格',
    content: '左小括号和字符之间不出现空格；同样，右小括号和字符之间也不出现空格。',
    exampleBad: 'if ( isOk ) {}',
    exampleGood: 'if (isOk) {}' },
  { code: '1.3.3', level: 'MANDATORY', category: '编程规约-格式',
    title: '运算符与操作数之间有空格',
    content: '任何二目、三目运算符的左右两边都需要加一个空格。',
    exampleBad: 'int c=a+b;',
    exampleGood: 'int c = a + b;' },
  { code: '1.3.4', level: 'MANDATORY', category: '编程规约-格式',
    title: '缩进 4 个空格，禁用 tab',
    content: '采用 4 个空格缩进，禁止使用 tab 字符。如使用 tab 缩进，必须设置 1 个 tab 为 4 个空格。' },
  { code: '1.3.5', level: 'MANDATORY', category: '编程规约-格式',
    title: '单行字符数限制不超过 120',
    content: '超出需要换行。换行时第二行相对第一行缩进 4 个空格，从第三行开始，不再继续缩进。运算符与下文一起换行，方法调用的点符号与下文一起换行，方法调用中的多个参数需要换行时在逗号后换行，括号前不要换行。' },
  { code: '1.3.6', level: 'MANDATORY', category: '编程规约-格式',
    title: '方法参数定义和传入时，多参数逗号后加空格',
    content: '方法参数在定义和传入时，多个参数逗号后边必须加空格。',
    exampleBad: 'f(a,b,c);',
    exampleGood: 'f(a, b, c);' },
  { code: '1.3.7', level: 'MANDATORY', category: '编程规约-格式',
    title: 'IDE 的 text file encoding 设置为 UTF-8',
    content: 'IDE 中文件的换行符使用 Unix 格式，不要使用 Windows 格式。' },
  { code: '1.3.8', level: 'RECOMMENDED', category: '编程规约-格式',
    title: '方法体内不同逻辑块用空行隔开',
    content: '方法体内的执行语句组、变量的定义语句组、不同的业务逻辑之间或者不同的语义之间插入一个空行。相同业务逻辑和语义之间不需要插入空行。' },
  { code: '1.3.9', level: 'RECOMMENDED', category: '编程规约-格式',
    title: '注释的双斜线与注释内容之间有且仅有一个空格',
    content: '单行注释双斜线和后面内容间有一个空格；星号和注释内容间也有一个空格。' },

  // ============ 一、编程规约 - (四) OOP 规约 ============
  { code: '1.4.1', level: 'MANDATORY', category: '编程规约-OOP',
    title: '避免通过一个类的对象引用访问此类的静态变量或静态方法',
    content: '访问静态变量或静态方法应通过类名访问，避免对象的无谓浪费。',
    exampleBad: 'new MyClass().STATIC_FIELD',
    exampleGood: 'MyClass.STATIC_FIELD' },
  { code: '1.4.2', level: 'MANDATORY', category: '编程规约-OOP',
    title: '所有的覆写方法必须加 @Override',
    content: '子类的覆写方法必须加 @Override 注解。加 @Override 可以准确判断是否覆写成功，编译阶段及时发现命名错误。' },
  { code: '1.4.3', level: 'MANDATORY', category: '编程规约-OOP',
    title: '相同参数类型、业务含义，才使用 Java 可变参数',
    content: '避免使用 Object。可变参数必须放置在参数列表的最后。提倡使用 List 传递更多参数。' },
  { code: '1.4.4', level: 'MANDATORY', category: '编程规约-OOP',
    title: '接口过时必须加 @Deprecated 注解',
    content: '对外提供的接口过时必须加上 @Deprecated 注解，并清晰说明采用的新接口或新服务是什么。' },
  { code: '1.4.5', level: 'MANDATORY', category: '编程规约-OOP',
    title: '不要使用过时的类或方法',
    content: '介绍过时的类或方法前应做好版本兼容调研，建议禁用或及时替换。' },
  { code: '1.4.6', level: 'MANDATORY', category: '编程规约-OOP',
    title: 'Object 的 equals 方法容易抛空指针异常',
    content: 'Object 的 equals 方法易抛空指针异常，应使用常量或确定有值的对象来调用 equals。推荐使用 JDK7 引入的 java.util.Objects#equals。',
    exampleBad: 'user.equals("foo")',
    exampleGood: '"foo".equals(user) // 或 Objects.equals(user, "foo")' },
  { code: '1.4.7', level: 'MANDATORY', category: '编程规约-OOP',
    title: '包装类对象之间用 equals 比较',
    content: '所有整型包装类对象之间值的比较，全部使用 equals 方法比较。==在两侧均为基本类型时比较值，但包装类 -128~127 范围内用 == 会命中 Integer 缓存，超过则是对象比较，不安全。' },
  { code: '1.4.8', level: 'MANDATORY', category: '编程规约-OOP',
    title: '基本类型和包装类型选择',
    content: '所有 POJO 类属性必须使用包装数据类型；RPC 方法的返回值和参数必须使用包装数据类型；所有局部变量使用基本数据类型。\n【说明】DB 查询结果可能是 null，用基本类型会 NPE；局部变量用基本类型减少自动拆装箱成本。' },
  { code: '1.4.9', level: 'MANDATORY', category: '编程规约-OOP',
    title: '定义 DO/DTO/VO 等 POJO 类时，不要设定任何属性默认值',
    content: '不设定默认值是为了避免应用场景误用。',
    exampleBad: 'private Integer count = 0;',
    exampleGood: 'private Integer count;' },
  { code: '1.4.10', level: 'MANDATORY', category: '编程规约-OOP',
    title: '序列化对象改造注意 serialVersionUID',
    content: 'serialVersionUID 不一致会抛出序列化运行时异常。如果完全不兼容升级应修改 serialVersionUID。' },
  { code: '1.4.11', level: 'MANDATORY', category: '编程规约-OOP',
    title: '构造方法里禁止加入任何业务逻辑',
    content: '如果有初始化逻辑，请放在 init 方法中。构造函数应简洁，复杂初始化会增加维护难度。' },
  { code: '1.4.12', level: 'MANDATORY', category: '编程规约-OOP',
    title: 'POJO 类必须重写 toString 方法',
    content: '使用 IDE 的中工具 source > generate toString 时，如继承了另一个 POJO 类，记得在前面加一个 super.toString()。抛异常时打印对象信息方便排查。' },

  // ============ 一、编程规约 - (五) 集合处理 ============
  { code: '1.5.1', level: 'MANDATORY', category: '编程规约-集合',
    title: '关于 hashCode 和 equals 的处理，遵循三原则',
    content: '1) 只要重写 equals，就必须重写 hashCode。2) Set 存储的是对象，所以这两个方法都要重写。3) 自定义对象作为 Map 的键，必须重写 hashCode 和 equals。' },
  { code: '1.5.2', level: 'MANDATORY', category: '编程规约-集合',
    title: 'ArrayList 的 subList 结果不可强转 ArrayList',
    content: 'subList 返回的是 ArrayList 的内部类 SubList，不是 ArrayList 本身。对 SubList 的修改会影响原列表，反之亦然。' },
  { code: '1.5.3', level: 'MANDATORY', category: '编程规约-集合',
    title: 'Arrays.asList 返回的 List 不可 add/remove',
    content: 'Arrays.asList 把数组转换成 List，这个 List 不能做修改操作。add/remove/clear 方法会抛 UnsupportedOperationException。',
    exampleBad: 'List<String> l = Arrays.asList("a","b");\nl.add("c"); // 抛异常',
    exampleGood: 'List<String> l = new ArrayList<>(Arrays.asList("a","b"));\nl.add("c");' },
  { code: '1.5.4', level: 'MANDATORY', category: '编程规约-集合',
    title: '在 subMap、tailMap、headMap 中注意返回结果是否包含边界',
    content: 'subMap(fromKey, toKey) 结果包含 fromKey 不包含 toKey；tailMap 包含 fromKey；headMap 不包含 toKey。' },
  { code: '1.5.5', level: 'MANDATORY', category: '编程规约-集合',
    title: '集合转数组的方法使用 toArray(T[] array)',
    content: '使用带泛型的 toArray，入参为 new T[0]。传入 new T[list.size()] 是早期 JDK 的不必要优化。',
    exampleGood: 'String[] arr = list.toArray(new String[0]);' },
  { code: '1.5.6', level: 'MANDATORY', category: '编程规约-集合',
    title: '使用 Collection 接口任何实现类的 addAll 方法时，要对输入的集合进行 NPE 判断',
    content: 'addAll(null) 会抛 NullPointerException。' },
  { code: '1.5.7', level: 'MANDATORY', category: '编程规约-集合',
    title: '使用 entrySet 遍历 Map，不要 keySet',
    content: 'keySet 遍历要先取 key 再 get value，查询 2 次；entrySet 只遍历 1 次即可。JDK8 推荐使用 Map.forEach。',
    exampleBad: 'for (String k : map.keySet()) { String v = map.get(k); ... }',
    exampleGood: 'for (Map.Entry<String, String> e : map.entrySet()) { ... }' },
  { code: '1.5.8', level: 'MANDATORY', category: '编程规约-集合',
    title: 'foreach 循环里不要进行元素的 remove/add 操作',
    content: 'foreach 内 remove 会抛 ConcurrentModificationException。remove 元素请使用 Iterator.remove 或 removeIf。',
    exampleBad: 'for (String s : list) { if (cond) list.remove(s); }',
    exampleGood: 'list.removeIf(s -> cond);' },
  { code: '1.5.9', level: 'MANDATORY', category: '编程规约-集合',
    title: 'Map/Set 中的 key 对象不可改变',
    content: '在 JDK7 版本及以上，Comparator 要满足 3 个条件：自反性、对称性、传递性，否则 Collections.sort、Arrays.sort 会抛 IllegalArgumentException。' },

  // ============ 一、编程规约 - (六) 并发处理 ============
  { code: '1.6.1', level: 'MANDATORY', category: '编程规约-并发',
    title: '获取单例对象需要保证线程安全',
    content: '获取单例对象需要保证线程安全，其中的方法也要保证线程安全。资源驱动类、工具类、单例工厂类都需要注意。' },
  { code: '1.6.2', level: 'MANDATORY', category: '编程规约-并发',
    title: '创建线程或线程池时请指定有意义的线程名称',
    content: '方便出错时回溯。使用 Guava 的 ThreadFactoryBuilder 或自定义 ThreadFactory。',
    exampleGood: 'new ThreadFactoryBuilder().setNameFormat("order-pool-%d").build()' },
  { code: '1.6.3', level: 'MANDATORY', category: '编程规约-并发',
    title: '线程资源必须通过线程池提供，不允许在应用中自行显式创建线程',
    content: '线程池能规避频繁创建销毁带来的资源开销问题；避免频繁创建销毁导致 OOM。' },
  { code: '1.6.4', level: 'MANDATORY', category: '编程规约-并发',
    title: '线程池不允许使用 Executors 创建',
    content: '不允许使用 Executors.newFixedThreadPool / newCachedThreadPool / newSingleThreadExecutor / newScheduledThreadPool；要通过 ThreadPoolExecutor 显式创建，规避资源耗尽风险（默认队列 Integer.MAX_VALUE 或线程数 Integer.MAX_VALUE）。',
    exampleBad: 'Executors.newFixedThreadPool(10); // 队列无界, OOM 风险',
    exampleGood: 'new ThreadPoolExecutor(10, 20, 60L, TimeUnit.SECONDS,\n    new LinkedBlockingQueue<>(1000),\n    new CustomThreadFactory("biz-"),\n    new ThreadPoolExecutor.CallerRunsPolicy());' },
  { code: '1.6.5', level: 'MANDATORY', category: '编程规约-并发',
    title: 'SimpleDateFormat 是线程不安全的',
    content: 'SimpleDateFormat 的 format 和 parse 都是非线程安全的，不要定义为 static；推荐 DateTimeFormatter（JDK8，线程安全）。',
    exampleBad: 'static SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");',
    exampleGood: 'static DateTimeFormatter FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd");' },
  { code: '1.6.6', level: 'MANDATORY', category: '编程规约-并发',
    title: '高并发时，同步调用应该去考量锁的性能损耗',
    content: '能用无锁数据结构就不要用锁；能锁区块就不要锁方法体；能锁对象就不要锁类。' },
  { code: '1.6.7', level: 'MANDATORY', category: '编程规约-并发',
    title: '多线程并行处理定时任务时，Timer 运行多个 TimeTask 时，只要其中之一没有捕获抛出的异常',
    content: '其它任务便会自动终止运行。使用 ScheduledExecutorService 替代。' },
  { code: '1.6.8', level: 'MANDATORY', category: '编程规约-并发',
    title: '对多个资源、数据库表、对象同时加锁时，需要保持一致的加锁顺序',
    content: '一致的加锁顺序否则可能造成死锁。' },
  { code: '1.6.9', level: 'MANDATORY', category: '编程规约-并发',
    title: '在使用阻塞等待获取锁的方式时，必须在 try 代码块之外调用 lock，并在 finally 中 unlock',
    content: '如果在 try 块之内进行加锁，若加锁失败 finally 会执行 unlock 造成 IllegalMonitorStateException。',
    exampleGood: 'lock.lock();\ntry {\n    // ...\n} finally {\n    lock.unlock();\n}' },
  { code: '1.6.10', level: 'MANDATORY', category: '编程规约-并发',
    title: '并发修改同一记录时，避免更新丢失，应使用乐观锁或悲观锁',
    content: '乐观锁：在表中增加 version 字段，更新时 WHERE version = #{version}；悲观锁：SELECT ... FOR UPDATE。' },
  { code: '1.6.11', level: 'MANDATORY', category: '编程规约-并发',
    title: '多线程场景下使用 Random 实例',
    content: 'Random 实例在多线程间共享性能差；推荐 ThreadLocalRandom。',
    exampleBad: 'Random r = new Random(); int n = r.nextInt();',
    exampleGood: 'int n = ThreadLocalRandom.current().nextInt();' },
  { code: '1.6.12', level: 'MANDATORY', category: '编程规约-并发',
    title: '通过双重检查锁实现延迟初始化的优化问题',
    content: '双重检查锁要求 volatile 修饰对象，防止 JVM 指令重排序。使用 JDK5 之后的静态内部类持有更简洁。' },
  { code: '1.6.13', level: 'MANDATORY', category: '编程规约-并发',
    title: 'volatile 保证可见性不保证原子性',
    content: 'i++ 这类复合操作在多线程下仍需加锁或使用 AtomicInteger；LongAdder 在高并发下比 AtomicLong 性能更好。' },

  // ============ 一、编程规约 - (七) 控制语句 ============
  { code: '1.7.1', level: 'MANDATORY', category: '编程规约-控制',
    title: 'switch 每个 case 要么通过 break/return 结束，要么注释说明继续执行到哪',
    content: '在 switch 块内，必须有 default 分支。' },
  { code: '1.7.2', level: 'MANDATORY', category: '编程规约-控制',
    title: 'if/else/for/while/do 必须使用大括号',
    content: '即使只有一行代码，避免使用单行的编码方式。',
    exampleBad: 'if (condition) statements;',
    exampleGood: 'if (condition) {\n    statements;\n}' },
  { code: '1.7.3', level: 'MANDATORY', category: '编程规约-控制',
    title: '在高并发场景中，避免使用"等于"判断作为中断或退出条件',
    content: '如果处理不当并发原子操作有误差，会造成死循环。',
    exampleBad: 'while (counter.get() == 100) {}',
    exampleGood: 'while (counter.get() >= 100) {}' },
  { code: '1.7.4', level: 'MANDATORY', category: '编程规约-控制',
    title: '循环体内字符串的连接方式使用 StringBuilder 的 append 方法',
    content: '循环体内 + 会反复创建 StringBuilder 对象。',
    exampleBad: 'String s = "";\nfor (...) { s += "x"; }',
    exampleGood: 'StringBuilder sb = new StringBuilder();\nfor (...) { sb.append("x"); }' },
  { code: '1.7.5', level: 'RECOMMENDED', category: '编程规约-控制',
    title: '多层嵌套应避免超过 3 层',
    content: '超过 3 层的 if-else 必须用状态设计模式、策略模式、卫语句或 Optional 避免。圈复杂度超过 10 应拆分。' },
  { code: '1.7.6', level: 'RECOMMENDED', category: '编程规约-控制',
    title: '除常用方法（如 getXxx/isXxx）等外，不要在条件判断中执行其它复杂的语句',
    content: '结果赋值给一个有意义的布尔变量，以提高可读性。',
    exampleBad: 'if ((file.isFile() && file.length() > 0) || (file.isDirectory() && file.list().length > 0)) {...}',
    exampleGood: 'boolean isNonEmpty = ...;\nif (isNonEmpty) { ... }' },
  { code: '1.7.7', level: 'MANDATORY', category: '编程规约-控制',
    title: '循环体中的语句要考量性能',
    content: '尽量减少在循环体中的对象创建、复杂方法调用、不必要的 try-catch。' },

  // ============ 一、编程规约 - (八) 注释规约 ============
  { code: '1.8.1', level: 'MANDATORY', category: '编程规约-注释',
    title: '类/类属性/类方法的注释必须使用 Javadoc 规范',
    content: '使用 /** 内容 */ 格式，不得使用 // xxx 方式。IDE 的文档注释会提示。' },
  { code: '1.8.2', level: 'MANDATORY', category: '编程规约-注释',
    title: '所有的抽象方法（包括接口中的方法）必须要用 Javadoc 注释',
    content: '除了返回值、参数、异常说明外，还必须指出该方法做什么事情，实现什么功能。' },
  { code: '1.8.3', level: 'MANDATORY', category: '编程规约-注释',
    title: '所有的类都必须添加创建者和创建日期',
    content: '@author / @date 标签，便于后续维护查找。' },
  { code: '1.8.4', level: 'MANDATORY', category: '编程规约-注释',
    title: '方法内部单行注释在被注释语句上方另起一行',
    content: '使用 // 注释。方法内部多行注释使用 /* */ 注释。注意与代码对齐。' },
  { code: '1.8.5', level: 'MANDATORY', category: '编程规约-注释',
    title: '所有的枚举类型字段必须要有注释，说明每个数据项的用途',
    content: '无论是枚举还是常量，都要说明枚举值代表什么含义。' },
  { code: '1.8.6', level: 'RECOMMENDED', category: '编程规约-注释',
    title: '与其"半吊子"英文来注释，不如用中文注释把问题说清楚',
    content: '注释的质量比数量更重要。专有名词可以保留英文。' },
  { code: '1.8.7', level: 'RECOMMENDED', category: '编程规约-注释',
    title: '代码修改的同时，注释也要进行相应的修改',
    content: '尤其是参数、返回值、异常、核心逻辑等的修改。' },
  { code: '1.8.8', level: 'REFERENCE', category: '编程规约-注释',
    title: '对于注释的要求',
    content: '1) 能够准确反映设计思想和代码逻辑。2) 能够描述业务含义，便于接手的同学快速读懂。' },
  { code: '1.8.9', level: 'REFERENCE', category: '编程规约-注释',
    title: '特殊注释标记',
    content: '待办用 // TODO: [name] 补充说明；临时解决用 // FIXME: [name] 问题描述。命中者要负责解决。' },

  // ============ 二、异常日志 - (一) 异常处理 ============
  { code: '2.1.1', level: 'MANDATORY', category: '异常日志-异常',
    title: '不要捕获 Java 类库中定义的继承自 RuntimeException 的运行时异常类',
    content: '如 IndexOutOfBoundsException / NullPointerException，应通过预检查避免。',
    exampleBad: 'try { return arr[i]; } catch (ArrayIndexOutOfBoundsException e) { return null; }',
    exampleGood: 'if (i >= 0 && i < arr.length) { return arr[i]; } else { return null; }' },
  { code: '2.1.2', level: 'MANDATORY', category: '异常日志-异常',
    title: '异常不要用来做流程控制、条件控制',
    content: '异常设计的初衷是解决程序运行中的各种意外情况，且异常的处理效率比条件判断低很多。' },
  { code: '2.1.3', level: 'MANDATORY', category: '异常日志-异常',
    title: 'catch 时请分清稳定代码和非稳定代码',
    content: '稳定代码指不可能出现异常的代码；非稳定代码 catch 时尽量精确，具体异常捕获，具体处理。' },
  { code: '2.1.4', level: 'MANDATORY', category: '异常日志-异常',
    title: '捕获异常是为了处理它，不要捕获了却什么都不处理而抛弃',
    content: '如果不想处理，请将该异常抛给它的调用者。最外层的业务使用者必须处理异常。',
    exampleBad: 'try { ... } catch (Exception e) { }',
    exampleGood: 'try { ... } catch (Exception e) {\n    log.error("操作失败, id={}", id, e);\n    throw new BusinessException("业务异常", e);\n}' },
  { code: '2.1.5', level: 'MANDATORY', category: '异常日志-异常',
    title: '有 try 块放到了事务代码中，catch 异常后，如果需要回滚事务',
    content: '一定要注意手动回滚事务。否则事务不会回滚。',
    exampleGood: 'TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();' },
  { code: '2.1.6', level: 'MANDATORY', category: '异常日志-异常',
    title: 'finally 块必须对资源对象、流对象进行关闭',
    content: '有异常也要做 try-catch。JDK7 以上版本建议使用 try-with-resources。',
    exampleGood: 'try (InputStream in = new FileInputStream(...)) {\n    // ...\n}' },
  { code: '2.1.7', level: 'MANDATORY', category: '异常日志-异常',
    title: '不要在 finally 块中使用 return',
    content: 'try 块 return 的语句执行成功后，并不会马上返回，而是继续执行 finally 块中的语句，如果此处有 return 语句，则在此直接返回。',
    exampleBad: 'try { return 1; } finally { return 2; } // 永远返回 2' },
  { code: '2.1.8', level: 'MANDATORY', category: '异常日志-异常',
    title: '捕获异常与抛异常，必须完全匹配，或者捕获异常是抛异常的父类',
    content: '不要把异常错抛出或压缩到一个不恰当的异常类型。' },
  { code: '2.1.9', level: 'MANDATORY', category: '异常日志-异常',
    title: '不能用 System.out 或 e.printStackTrace 输出异常',
    content: '异常栈信息会写入标准错误输出，会影响查询效率。必须用日志框架输出到日志文件。',
    exampleBad: 'e.printStackTrace();',
    exampleGood: 'log.error("操作失败, id={}", id, e);' },
  { code: '2.1.10', level: 'MANDATORY', category: '异常日志-异常',
    title: '方法的返回值可以为 null，不强制返回空集合或者空对象等',
    content: '必须添加注释充分说明什么情况下会返回 null。防止 NPE 是调用者的责任。' },
  { code: '2.1.11', level: 'MANDATORY', category: '异常日志-异常',
    title: '防止 NPE',
    content: '1) 自动拆箱引发的 NPE。2) 数据库查询结果可能为 null。3) 集合元素可能为 null。4) 远程调用返回值要用 Optional 来防止 NPE。' },

  // ============ 二、异常日志 - (二) 日志规约 ============
  { code: '2.2.1', level: 'MANDATORY', category: '异常日志-日志',
    title: '应用中不可直接使用日志系统（Log4j、Logback）中的 API',
    content: '应依赖使用日志框架 SLF4J 中的 API，使用门面模式的日志框架，有利于维护和各个类的日志处理方式统一。',
    exampleGood: 'import org.slf4j.Logger;\nimport org.slf4j.LoggerFactory;\nprivate static final Logger log = LoggerFactory.getLogger(Xxx.class);' },
  { code: '2.2.2', level: 'MANDATORY', category: '异常日志-日志',
    title: '日志文件至少保存 15 天',
    content: '因为有些异常具备以"周"为频次发生的特点。线上日志必须符合此规约。' },
  { code: '2.2.3', level: 'MANDATORY', category: '异常日志-日志',
    title: '日志打印时禁止直接用 JSON 工具将对象转换成 String',
    content: '应用 toString。如果对象有死循环或类加载冲突的问题，会抛出异常。' },
  { code: '2.2.4', level: 'MANDATORY', category: '异常日志-日志',
    title: '日志输出时，字符串变量之间的拼接使用占位符',
    content: '用占位符可以减少字符串拼接的对象创建。',
    exampleBad: 'log.info("用户 " + user + " 登录");',
    exampleGood: 'log.info("用户 {} 登录", user);' },
  { code: '2.2.5', level: 'MANDATORY', category: '异常日志-日志',
    title: '对于 trace/debug/info 级别的日志输出，必须使用条件输出形式或占位符',
    content: 'trace 和 debug 一定要判断 isDebugEnabled，防止无效的字符串拼接。info 用占位符即可。' },
  { code: '2.2.6', level: 'MANDATORY', category: '异常日志-日志',
    title: '异常信息应该包括两类信息：案发现场信息和异常堆栈信息',
    content: '如果不处理，那么通过关键字 throws 往上抛出。',
    exampleGood: 'log.error("处理订单失败, orderId={}, userId={}", orderId, userId, e);' },
  { code: '2.2.7', level: 'RECOMMENDED', category: '异常日志-日志',
    title: '谨慎地记录日志',
    content: '生产环境禁止输出 debug 日志；有选择地输出 info 日志。如果大量输出，担心性能开销和磁盘空间。' },
  { code: '2.2.8', level: 'RECOMMENDED', category: '异常日志-日志',
    title: '可以使用 warn 日志记录用户输入参数错误的情况',
    content: '避免用户投诉时查询问题困难。如非必要，请不要在此场景下抛出异常。' },

  // ============ 三、单元测试 ============
  { code: '3.1', level: 'MANDATORY', category: '单元测试',
    title: 'AIR 原则：Automatic、Independent、Repeatable',
    content: '好的单元测试必须自动执行（断言而非 println）、独立（不依赖其他测试）、可重复（执行多次结果相同）。' },
  { code: '3.2', level: 'MANDATORY', category: '单元测试',
    title: '单元测试应该是全自动执行的，并且非交互式的',
    content: '测试框架通常是定期执行，禁止输出日志需要人工检验。' },
  { code: '3.3', level: 'MANDATORY', category: '单元测试',
    title: '保持单元测试的独立性',
    content: '为了保证单元测试稳定可靠且便于维护，单元测试用例之间不得互相调用，也不得依赖执行的先后次序。' },
  { code: '3.4', level: 'MANDATORY', category: '单元测试',
    title: '单元测试是可以重复执行的',
    content: '不能受到外界环境的影响（如外部数据库、Redis、MQ）。必须用 Mock 方式。' },
  { code: '3.5', level: 'MANDATORY', category: '单元测试',
    title: '对于单元测试，要保证测试粒度足够小',
    content: '有助于精确定位问题。单元测试粒度至多是类级别，一般是方法级别。' },
  { code: '3.6', level: 'MANDATORY', category: '单元测试',
    title: '核心业务、核心应用、核心模块的增量代码确保单元测试通过',
    content: '新增代码及时补充单元测试。新增代码未做单元测试，不允许合并到 master/trunk。' },
  { code: '3.7', level: 'MANDATORY', category: '单元测试',
    title: '单元测试代码必须写在如下工程目录：src/test/java',
    content: '不允许写在业务代码目录下。' },
  { code: '3.8', level: 'RECOMMENDED', category: '单元测试',
    title: '单元测试的基本原则是：一个方法对应多种不同的输入',
    content: 'BCDE 原则：Border 边界值；Correct 正确；Design 设计相符；Error 强制错误信息输入。' },
  { code: '3.9', level: 'RECOMMENDED', category: '单元测试',
    title: '对于数据库相关的查询、更新、删除等操作，不要以为结果一定成功',
    content: '使用程序抽样或日志校验法来验证数据。' },
  { code: '3.10', level: 'REFERENCE', category: '单元测试',
    title: '对于不可测的代码建议做必要的重构',
    content: '使代码变得可测试，避免为了代码而做单元测试。' },

  // ============ 四、安全规约 ============
  { code: '4.1', level: 'MANDATORY', category: '安全规约',
    title: '隶属于用户个人的页面或功能必须进行权限控制校验',
    content: '防止越权访问。不做校验就可能导致越权数据访问。' },
  { code: '4.2', level: 'MANDATORY', category: '安全规约',
    title: '用户敏感数据禁止直接展示，必须脱敏',
    content: '手机号、身份证、银行卡号、地址、邮箱等敏感字段在前端展示时要脱敏。',
    exampleBad: 'log.info("手机号: {}", phone);',
    exampleGood: 'log.info("手机号: {}", DesensitizedUtil.mobile(phone));\n// 显示 138****8888' },
  { code: '4.3', level: 'MANDATORY', category: '安全规约',
    title: '用户请求传入的任何参数必须做有效性验证',
    content: '忽略参数校验可能导致 page size 过大拖慢数据库性能、任意重定向、SQL 注入、反序列化注入、正则 ReDoS 等。' },
  { code: '4.4', level: 'MANDATORY', category: '安全规约',
    title: '禁止向 HTML 页面输出未经安全过滤或未正确转义的用户数据',
    content: '否则易触发 XSS（跨站脚本攻击）。' },
  { code: '4.5', level: 'MANDATORY', category: '安全规约',
    title: '表单、AJAX 提交必须执行 CSRF 安全过滤',
    content: 'CSRF（Cross-site request forgery）攻击通过伪造用户身份构造网络请求。必须带上 csrf token 校验。' },
  { code: '4.6', level: 'MANDATORY', category: '安全规约',
    title: '在使用平台资源，譬如短信、邮件、电话、下单、支付，必须实现正确的防重放的机制',
    content: '限制调用频率：滑动窗口、分布式限流、验证码校验、幂等 key。' },
  { code: '4.7', level: 'MANDATORY', category: '安全规约',
    title: '发贴、评论、发送即时消息等用户生成内容，必须实现防刷、文本内容违禁词过滤',
    content: '涉黄、涉政、涉恐、暴力、敏感词检测在提交入口拦截。' },
  { code: '4.8', level: 'MANDATORY', category: '安全规约',
    title: '应用中的密码、私密信息的加密算法避免使用 DES',
    content: 'DES 加密算法被视作已被破解的加密算法。AES 256/192/128 是推荐算法。' },
  { code: '4.9', level: 'MANDATORY', category: '安全规约',
    title: '禁止使用硬编码（hardcode）的方式将密钥或密码写入代码',
    content: '应通过加密的配置文件、密钥管理服务（KMS）、环境变量等方式管理。项目用 Jasypt 加密 bootstrap.yml 即是此目的。' },
  { code: '4.10', level: 'MANDATORY', category: '安全规约',
    title: '用户输入的 SQL 参数严格使用参数绑定',
    content: '使用 MyBatis 的 #{} 代替 ${}；JDBC 用 PreparedStatement。字符串拼接 SQL 会导致 SQL 注入。',
    exampleBad: 'String sql = "SELECT * FROM user WHERE id=" + userId;',
    exampleGood: 'SELECT * FROM user WHERE id = #{userId}' },
  { code: '4.11', level: 'MANDATORY', category: '安全规约',
    title: '对于文件上传功能',
    content: '1) 限制扩展名（白名单）。2) 限制 Content-Type。3) 文件名随机化。4) 存储到非 Web 根目录。5) 限制文件大小。' },
  { code: '4.12', level: 'MANDATORY', category: '安全规约',
    title: '反序列化不可信数据易造成 RCE',
    content: '不要反序列化不可信来源的数据（如 Apache Commons Collections 的 readObject 漏洞）；用白名单过滤可反序列化的类。' },

  // ============ 五、MySQL 数据库 - (一) 建表规约 ============
  { code: '5.1.1', level: 'MANDATORY', category: 'MySQL-建表',
    title: '表达是与否概念的字段，必须使用 is_xxx 的方式命名，数据类型 unsigned tinyint',
    content: '1 表示是，0 表示否。任何字段如果为非负数，必须是 unsigned。' },
  { code: '5.1.2', level: 'MANDATORY', category: 'MySQL-建表',
    title: '表名、字段名必须使用小写字母或数字',
    content: '禁止出现数字开头，禁止两个下划线中间只出现数字。MySQL 在 Windows 不区分大小写，但在 Linux 默认区分。' },
  { code: '5.1.3', level: 'MANDATORY', category: 'MySQL-建表',
    title: '表名不使用复数名词',
    content: '表名应该仅仅表示表里面的实体内容。' },
  { code: '5.1.4', level: 'MANDATORY', category: 'MySQL-建表',
    title: '禁用保留字',
    content: '如 desc / range / match / delayed 等，参考 MySQL 官方保留字。' },
  { code: '5.1.5', level: 'MANDATORY', category: 'MySQL-建表',
    title: '主键索引名为 pk_字段名；唯一索引名为 uk_字段名；普通索引名则为 idx_字段名',
    content: 'pk_ primary key；uk_ unique key；idx_ index。' },
  { code: '5.1.6', level: 'MANDATORY', category: 'MySQL-建表',
    title: '小数类型为 decimal，禁止使用 float 和 double',
    content: 'float 和 double 在存储时存在精度损失问题，很可能在值的比较时得到不正确的结果。如果存储的数据范围超过 decimal 的范围，建议将数据拆成整数和小数分开存储。' },
  { code: '5.1.7', level: 'MANDATORY', category: 'MySQL-建表',
    title: '如果存储的字符串长度几乎相等，使用 char 定长字符串类型',
    content: 'varchar 是可变长字符串，不预先分配存储空间，长度不要超过 5000。超过的建议独立出表，用主键关联。' },
  { code: '5.1.8', level: 'MANDATORY', category: 'MySQL-建表',
    title: '表必备三字段：id、create_time、update_time',
    content: 'id 必为主键，类型为 bigint unsigned、单表时自增、步长为 1。create_time、update_time 的类型均为 datetime。' },
  { code: '5.1.9', level: 'RECOMMENDED', category: 'MySQL-建表',
    title: '表的命名最好是加上"业务名称_表的作用"',
    content: '便于分库分表时自动路由。',
    exampleGood: 'alipay_task / force_project / trade_config' },
  { code: '5.1.10', level: 'RECOMMENDED', category: 'MySQL-建表',
    title: '库名与应用名称尽量一致',
    content: '数据库名、表名在业务上要保持一致。' },
  { code: '5.1.11', level: 'RECOMMENDED', category: 'MySQL-建表',
    title: '如果修改字段含义或对字段表示的状态追加时，需要及时更新字段注释',
    content: '增加字段注释以保持业务含义清晰。' },
  { code: '5.1.12', level: 'RECOMMENDED', category: 'MySQL-建表',
    title: '字段允许适当冗余，以提高查询性能',
    content: '但必须考虑数据一致性。冗余字段应遵循：1) 不是频繁修改的字段。2) 不是 varchar 超长字段，更不能是 text 字段。' },
  { code: '5.1.13', level: 'RECOMMENDED', category: 'MySQL-建表',
    title: '单表行数超过 500 万行或者单表容量超过 2GB，才推荐进行分库分表',
    content: '如果预计三年后的数据量根本达不到这个级别，请不要在创建表时就分库分表。' },

  // ============ 五、MySQL 数据库 - (二) 索引规约 ============
  { code: '5.2.1', level: 'MANDATORY', category: 'MySQL-索引',
    title: '业务上具有唯一特性的字段，即使是组合字段，也必须建成唯一索引',
    content: '索引既有助于查询优化器生成高效的执行计划，又能保证数据的唯一性。' },
  { code: '5.2.2', level: 'MANDATORY', category: 'MySQL-索引',
    title: '超过三个表禁止 join',
    content: 'join 的字段，数据类型必须绝对一致；多表关联查询时，保证被关联的字段需要有索引。' },
  { code: '5.2.3', level: 'MANDATORY', category: 'MySQL-索引',
    title: '在 varchar 字段上建立索引时，必须指定索引长度',
    content: '没必要对全字段建立索引，根据实际文本区分度决定索引长度即可。一般对字符串类型数据，长度为 20 的索引区分度可达 90% 以上。' },
  { code: '5.2.4', level: 'MANDATORY', category: 'MySQL-索引',
    title: '页面搜索严禁左模糊或者全模糊，如果需要请走搜索引擎来解决',
    content: 'LIKE %xx 和 LIKE %xx% 都会使索引失效，走全表扫描。' },
  { code: '5.2.5', level: 'RECOMMENDED', category: 'MySQL-索引',
    title: '如果有 order by 的场景，请注意利用索引的有序性',
    content: 'order by 最后的字段是组合索引的一部分，并且放在索引组合顺序的最后，避免出现 file_sort 的情况，影响查询性能。' },
  { code: '5.2.6', level: 'RECOMMENDED', category: 'MySQL-索引',
    title: '利用覆盖索引来进行查询操作，避免回表',
    content: '能够建立索引的种类分为主键索引、唯一索引、普通索引三种。覆盖索引指查询的字段都在索引中。' },
  { code: '5.2.7', level: 'RECOMMENDED', category: 'MySQL-索引',
    title: '利用延迟关联或者子查询优化超多分页场景',
    content: 'MySQL 并不是跳过 offset 行，而是取 offset+N 行然后返回放弃前 offset 行。当 offset 特别大时效率差。',
    exampleBad: 'SELECT * FROM t WHERE a=1 ORDER BY id LIMIT 100000, 10;',
    exampleGood: 'SELECT * FROM t a JOIN (SELECT id FROM t WHERE a=1 ORDER BY id LIMIT 100000, 10) b ON a.id = b.id;' },
  { code: '5.2.8', level: 'RECOMMENDED', category: 'MySQL-索引',
    title: 'SQL 性能优化的目标：至少要达到 range 级别，要求是 ref 级别，如果可以是 const 最好',
    content: 'consts 单表中最多只有一个匹配行（主键或唯一索引）；ref 使用普通索引；range 对索引进行范围检索。' },
  { code: '5.2.9', level: 'RECOMMENDED', category: 'MySQL-索引',
    title: '建组合索引的时候，区分度最高的在最左边',
    content: '例如 where a=? and b=? 如果 a 列几乎接近于唯一值，那么只需要单建 idx_a。' },
  { code: '5.2.10', level: 'REFERENCE', category: 'MySQL-索引',
    title: '创建索引时避免有如下极端误解',
    content: '1) 不要宁滥勿缺，认为一个查询就需要建一个索引。2) 不要吝啬索引创建，认为索引会消耗空间。3) 不要抵制唯一索引，认为业务的唯一性一律需要在应用层通过"先查后插"方式完成。' },

  // ============ 五、MySQL 数据库 - (三) SQL 规约 ============
  { code: '5.3.1', level: 'MANDATORY', category: 'MySQL-SQL',
    title: '不要使用 count(列名) 或 count(常量) 来替代 count(*)',
    content: 'count(*) 是 SQL92 定义的标准统计行数的语法，跟数据库无关，跟 NULL 和非 NULL 无关。count(*) 会统计值为 NULL 的行，而 count(列名) 不会。' },
  { code: '5.3.2', level: 'MANDATORY', category: 'MySQL-SQL',
    title: 'count(distinct col) 计算该列除 NULL 之外的不重复行数',
    content: '注意 count(distinct col1, col2) 如果其中一列全为 NULL，那么即使另一列有不同的值，也返回为 0。' },
  { code: '5.3.3', level: 'MANDATORY', category: 'MySQL-SQL',
    title: '当某一列的值全是 NULL 时，count(col) 的返回结果为 0',
    content: '但 sum(col) 的返回结果为 NULL，因此使用 sum() 时需注意 NPE 问题。',
    exampleGood: 'SELECT IF(ISNULL(SUM(g)), 0, SUM(g)) FROM table;' },
  { code: '5.3.4', level: 'MANDATORY', category: 'MySQL-SQL',
    title: '使用 ISNULL() 来判断是否为 NULL 值',
    content: 'NULL 与任何值比较都为 NULL。包括 NULL=NULL、NULL<>NULL 的返回结果都是 NULL。' },
  { code: '5.3.5', level: 'MANDATORY', category: 'MySQL-SQL',
    title: '在代码中写分页查询逻辑时，若 count 为 0 应直接返回',
    content: '避免执行后面的分页语句。数据库压力和应用性能都更优。' },
  { code: '5.3.6', level: 'MANDATORY', category: 'MySQL-SQL',
    title: '不得使用外键与级联，一切外键概念必须在应用层解决',
    content: '外键与级联更新不适合分布式、高并发集群。级联更新是强阻塞，存在数据库更新风暴的风险。' },
  { code: '5.3.7', level: 'MANDATORY', category: 'MySQL-SQL',
    title: '禁止使用存储过程',
    content: '存储过程难以调试和扩展，更没有移植性。' },
  { code: '5.3.8', level: 'MANDATORY', category: 'MySQL-SQL',
    title: '数据订正时，删除和修改记录时，要先 select，避免出现误删除',
    content: '确认无误才能执行更新语句。生产环境禁止使用 delete from 不带 where 条件。' },
  { code: '5.3.9', level: 'RECOMMENDED', category: 'MySQL-SQL',
    title: 'in 操作能避免则避免，若实在避免不了，需要仔细评估 in 后边的集合元素数量',
    content: '控制在 1000 个之内。否则 MySQL 会将 IN 查询放到一个临时表，影响性能。' },
  { code: '5.3.10', level: 'REFERENCE', category: 'MySQL-SQL',
    title: '因国际化需要，所有的字符存储与表示，均以 utf-8 编码',
    content: 'utf8mb4 能完整支持 Unicode 编码，包括 emoji；utf8 仅支持 3 字节 UTF-8。' },

  // ============ 五、MySQL 数据库 - (四) ORM 映射 ============
  { code: '5.4.1', level: 'MANDATORY', category: 'MySQL-ORM',
    title: '在表查询中，一律不要使用 * 作为查询的字段列表',
    content: '需要哪些字段必须明确写明。1) 增加查询分析器解析成本。2) 增减字段容易与 resultMap 配置不一致。',
    exampleBad: 'SELECT * FROM user',
    exampleGood: 'SELECT id, name, email FROM user' },
  { code: '5.4.2', level: 'MANDATORY', category: 'MySQL-ORM',
    title: 'POJO 类的布尔属性不能加 is，而数据库字段必须加 is_',
    content: '要求在 resultMap 中进行字段与属性之间的映射。' },
  { code: '5.4.3', level: 'MANDATORY', category: 'MySQL-ORM',
    title: '不要用 resultClass 当返回参数，即使所有类属性名与数据库字段一一对应',
    content: '也需要定义；反过来，每一个表也必然有一个与之对应的 POJO。' },
  { code: '5.4.4', level: 'MANDATORY', category: 'MySQL-ORM',
    title: 'sql.xml 配置参数使用 #{}，#param#',
    content: '不要使用 ${}，此种方式容易出现 SQL 注入。',
    exampleBad: 'WHERE name LIKE \'%${name}%\'',
    exampleGood: 'WHERE name LIKE CONCAT(\'%\', #{name}, \'%\')' },
  { code: '5.4.5', level: 'MANDATORY', category: 'MySQL-ORM',
    title: 'iBATIS 自带的 queryForList(String statementName, int start, int size)',
    content: '不推荐使用。其实现方式是在数据库取到 statementName 对应 SQL 语句的所有记录，再通过 subList 取 start、size 的子集。' },
  { code: '5.4.6', level: 'MANDATORY', category: 'MySQL-ORM',
    title: '不允许直接拿 HashMap 与 HashTable 作为查询结果集的输出',
    content: 'resultClass=hashmap，会置入字段名和属性值，但是值的类型不可控。' },
  { code: '5.4.7', level: 'MANDATORY', category: 'MySQL-ORM',
    title: '更新数据表记录时，必须同时更新记录对应的 gmt_modified 字段值为当前时间',
    content: '或者交由数据库 ON UPDATE CURRENT_TIMESTAMP 自动维护。' },
  { code: '5.4.8', level: 'RECOMMENDED', category: 'MySQL-ORM',
    title: '不要写一个大而全的数据更新接口',
    content: '传入为 POJO 类，不管是不是自己的目标更新字段，都进行 update table set c1=value1, c2=value2 执行时，不仅效率不高，而且易出错。' },
  { code: '5.4.9', level: 'REFERENCE', category: 'MySQL-ORM',
    title: '@Transactional 事务不要滥用',
    content: '事务会影响数据库的 QPS，另外使用事务的地方需要考虑各方面的回滚方案。' },
  { code: '5.4.10', level: 'REFERENCE', category: 'MySQL-ORM',
    title: 'iBATIS/MyBatis 中的 <isEqual> 中的 compareValue 是与属性值对比的常量',
    content: '一般为数字，表示相等时带上此条件；<isNotEmpty> 表示不为空且不为 null 时执行；<isNotNull> 表示不为 null 值时执行。' },

  // ============ 六、工程结构 ============
  { code: '6.1', level: 'MANDATORY', category: '工程结构',
    title: '应用分层',
    content: '分层调用：Controller → Service → Manager → DAO；不能跨层调用（如 Controller 直接调 DAO）；Service 和 Manager 之间的调用不允许循环调用。' },
  { code: '6.2', level: 'RECOMMENDED', category: '工程结构',
    title: '分层领域模型规约',
    content: 'DO（Data Object）：与数据库表结构一一对应。DTO（Data Transfer Object）：数据传输对象。BO（Business Object）：业务对象。AO（Application Object）：应用对象。VO（View Object）：显示层对象。Query：数据查询对象。' },
  { code: '6.3', level: 'RECOMMENDED', category: '工程结构',
    title: '二方库命名规约',
    content: 'GAV 遵从以下规则：GroupID 格式 com.{公司/BU}.{业务线}；ArtifactID 格式 产品线名-模块名；Version 规约：主版本号.次版本号.修订号。' },
  { code: '6.4', level: 'MANDATORY', category: '工程结构',
    title: '定义 GAV 遵从以下规则',
    content: 'GroupID 格式：com.{公司/BU}.业务线.[子业务线]，最多 4 级。ArtifactID 格式：产品线-模块名，语义不重复。Version：主版本号.次版本号.修订号（x.y.z）。' },
  { code: '6.5', level: 'MANDATORY', category: '工程结构',
    title: '二方库版本号命名方式：主版本号.次版本号.修订号',
    content: '1) 主版本号：产品方向改变，或者大规模 API 不兼容，或者架构不兼容升级。2) 次版本号：保持相对兼容性，增加主要功能特性。3) 修订号：保持完全兼容性，修复 bug、新增次要功能特性等。' },
  { code: '6.6', level: 'MANDATORY', category: '工程结构',
    title: '线上应用不要依赖 SNAPSHOT 版本',
    content: '不依赖的话需要更新 maven 依赖到 Release 版本。' },
  { code: '6.7', level: 'MANDATORY', category: '工程结构',
    title: '二方库的新增或升级，保持除功能点之外的其它 jar 包仲裁结果不变',
    content: '如果有改变，必须说明潜在风险与影响。jar 包仲裁冲突时，在 maven dependency:tree 中清晰查找。' },
  { code: '6.8', level: 'RECOMMENDED', category: '工程结构',
    title: '二方库里可以定义枚举类型，参数也可以使用枚举类型',
    content: '但接口返回值不允许使用枚举类型或者包含枚举类型的 POJO 对象。' },
  { code: '6.9', level: 'RECOMMENDED', category: '工程结构',
    title: '接口发布规约',
    content: '1) 公共组件类、底层类型必须声明 @Deprecated 注解，并在 Javadoc 里说明替代的新接口。2) 过时接口必须保证在下一个版本继续支持。' },
  { code: '6.10', level: 'REFERENCE', category: '工程结构',
    title: '不要在子项目的 pom 依赖中出现相同的 GroupId，相同的 ArtifactId，但是不同的 Version',
    content: '这种情况可能导致版本冲突问题，让版本仲裁结果不可预料。' },

  // ============ 七、设计规约 ============
  { code: '7.1', level: 'MANDATORY', category: '设计规约',
    title: '存储方案和底层数据结构的设计获得评审一致通过，并沉淀成为文档',
    content: '有缜密的方案设计要比在添加功能时中途发现问题更要系统、专业、合理。否则迟早会出性能问题或设计反复。' },
  { code: '7.2', level: 'MANDATORY', category: '设计规约',
    title: '在需求分析阶段，如果与系统交互的 User 超过一类并且相关的 User Case 超过 5 个',
    content: '使用用例图来表达更加清晰的结构化需求。' },
  { code: '7.3', level: 'MANDATORY', category: '设计规约',
    title: '如果某个业务对象的状态超过 3 个，使用状态图来表达并且明确状态变化的各个触发条件',
    content: '状态图的核心是对象状态，触发条件和标识转化的行为。' },
  { code: '7.4', level: 'MANDATORY', category: '设计规约',
    title: '如果系统中某个功能的调用链路上的涉及对象超过 3 个，使用时序图来表达并且明确各调用环节的输入与输出',
    content: '时序图反映了一系列对象间的交互与协作关系，清晰立体地反映系统的调用纵深链路。' },
  { code: '7.5', level: 'MANDATORY', category: '设计规约',
    title: '如果系统中模型类超过 5 个，并且存在复杂的依赖关系，使用类图来表达并明确类之间的关系',
    content: '类图像建筑领域的施工图，它的价值与需求文档等价。' },
  { code: '7.6', level: 'MANDATORY', category: '设计规约',
    title: '如果系统中超过 2 个对象之间存在协作关系，并且需要表示复杂的处理流程',
    content: '使用活动图来表示。活动图是流程图的扩展，增加了能够体现协作关系的对象分区、同步条等要素。' },
  { code: '7.7', level: 'RECOMMENDED', category: '设计规约',
    title: '类在设计时要遵循六大原则 SOLID',
    content: '1) 单一职责原则（SRP）2) 开闭原则（OCP）3) 里氏替换原则（LSP）4) 接口隔离原则（ISP）5) 依赖倒置原则（DIP）6) 迪米特法则（LoD）。' },
  { code: '7.8', level: 'RECOMMENDED', category: '设计规约',
    title: '在做系统设计时，可以预留扩展接口，方便未来或其它业务方平滑接入',
    content: '但是，不要过度设计，抽象会导致复杂。' },
  { code: '7.9', level: 'RECOMMENDED', category: '设计规约',
    title: '设计时有意识地在代码中体现设计模式',
    content: '但不要为了用设计模式而用设计模式。' },
  { code: '7.10', level: 'REFERENCE', category: '设计规约',
    title: '避免如下误区：NeedsDesign',
    content: '1) 一切从零开始：已有的解决方案不采用；2) 过度设计：早期即考虑各种复杂场景；3) 僵化设计：认为设计完美无需变更。' },
  { code: '7.11', level: 'REFERENCE', category: '设计规约',
    title: '方法行数建议控制在 80 行以内',
    content: '超过 80 行请考虑拆分；一般而言，一个方法只做一件事。' },
  { code: '7.12', level: 'REFERENCE', category: '设计规约',
    title: '圈复杂度控制在 10 以内',
    content: '圈复杂度越高，代码的可理解性越差，缺陷越多。高于 10 强制拆分。' },

  // ============ 八、日期时间（黄山版新增）============
  { code: '8.1', level: 'MANDATORY', category: '日期时间',
    title: '日期格式化时，传入 pattern 中表示年份统一使用小写的 y',
    content: '大写 Y 表示 Week Year，容易在跨年的 12 月 31 日到 1 月 2 日之间出现错误结果。',
    exampleBad: 'new SimpleDateFormat("YYYY-MM-dd"); // 跨年可能出错',
    exampleGood: 'new SimpleDateFormat("yyyy-MM-dd");' },
  { code: '8.2', level: 'MANDATORY', category: '日期时间',
    title: '在日期格式中，分清楚大写的 M 和小写的 m；大写的 H 和小写的 h 分别指代的意义',
    content: 'M 表示月，m 表示分钟；H 是 24 小时制，h 是 12 小时制。' },
  { code: '8.3', level: 'MANDATORY', category: '日期时间',
    title: '获取当前毫秒数：System.currentTimeMillis() 而不是 new Date().getTime()',
    content: '更简洁，避免不必要的对象创建。需要秒级精度用 Instant.now().getEpochSecond()。' },
  { code: '8.4', level: 'MANDATORY', category: '日期时间',
    title: '不允许在程序任何地方中使用：1) java.sql.Date 2) java.sql.Time 3) java.sql.Timestamp',
    content: '这三个类继承自 java.util.Date，但内部存的是 UTC 时间，与 util.Date 有区别。统一用 java.time 包。' },
  { code: '8.5', level: 'MANDATORY', category: '日期时间',
    title: '不要在程序中写死一年为 365 天',
    content: '有些年份是 366 天（闰年）。用 LocalDate / Period 做日期运算。',
    exampleBad: 'long oneYear = 365 * 24 * 3600 * 1000L;',
    exampleGood: 'Period.ofYears(1); // 或 YearMonth.lengthOfYear()' },
  { code: '8.6', level: 'RECOMMENDED', category: '日期时间',
    title: '避免公历闰年 2 月出现的日期越界',
    content: '比如 LocalDate.of(2020, 2, 29).plusYears(1) 会得到 2021-02-28。用 plusYears 时注意非闰年。' },
  { code: '8.7', level: 'RECOMMENDED', category: '日期时间',
    title: '使用枚举值来指代月份',
    content: 'Month 枚举值从 1 开始（1-12）；Calendar 的月份从 0 开始（0-11），容易出错。用 java.time.Month 避免歧义。' },
  { code: '8.8', level: 'MANDATORY', category: '日期时间',
    title: '日期时间计算尽量使用 JSR-310 的 LocalDate / LocalDateTime',
    content: 'JDK8 引入的 java.time 包是不可变的、线程安全的、API 友好的日期时间类，取代老旧的 Date/Calendar。' },

  // ============ 九、前后端规约（黄山版新增）============
  { code: '9.1', level: 'MANDATORY', category: '前后端规约',
    title: '前后端交互的 API，需要明确协议、域名、路径、请求方法、请求内容、状态码、响应体',
    content: '1) 协议：生产环境务必使用 HTTPS。2) 路径：代表某功能的资源表述，用 kebab-case。3) 请求方法：符合 RESTful 语义。4) 状态码：2xx 成功，3xx 重定向，4xx 客户端错误，5xx 服务端错误。' },
  { code: '9.2', level: 'MANDATORY', category: '前后端规约',
    title: '前后端数据列表相关的接口返回，如果为空，则返回空数组 [] 或空集合 {}',
    content: '不要返回 null。避免前端再判断 null。' },
  { code: '9.3', level: 'MANDATORY', category: '前后端规约',
    title: '服务端发生错误时，返回给前端的响应信息必须包含 HTTP 状态码、errorCode、errorMessage、用户提示信息',
    content: '错误表意需符合 RESTful 规范，前端可根据这些信息做差异化处理。' },
  { code: '9.4', level: 'MANDATORY', category: '前后端规约',
    title: '在 URL 中，用于标识唯一资源的参数，采用 Path Variables 方式',
    content: 'https://domain/tradeOrderId={}（错）；https://domain/tradeOrder/{tradeOrderId}（对）。过滤、搜索信息用 Query Parameters。' },
  { code: '9.5', level: 'MANDATORY', category: '前后端规约',
    title: '对于需要使用超链接的场景，必须使用绝对路径作为 URL',
    content: '防止前缀丢失或重定向导致的链接失效。' },
  { code: '9.6', level: 'MANDATORY', category: '前后端规约',
    title: '页面输出带有敏感类数据：卡号、电话等要考虑脱敏',
    content: '应用内控制：前后端都要脱敏展示和日志记录。' },
  { code: '9.7', level: 'MANDATORY', category: '前后端规约',
    title: '前端提交的数据必须在后端做二次校验，不能仅靠前端校验',
    content: '前端校验只是为了用户体验，不能作为安全防线。' },
  { code: '9.8', level: 'MANDATORY', category: '前后端规约',
    title: '在翻页场景中，用户输入参数的小于 1，则前端返回第一页',
    content: '参数大于尾页，则前端返回最后一页。避免展示"无数据"的窘况。' },
  { code: '9.9', level: 'RECOMMENDED', category: '前后端规约',
    title: '页面上需要对操作进行二次确认（delete / update / save），避免误操作',
    content: '尤其是删除操作，必须弹框确认。' },
  { code: '9.10', level: 'RECOMMENDED', category: '前后端规约',
    title: '在 URL 中，用于操作的动作，采用动词',
    content: '获取列表用 GET /users；获取单个用 GET /users/{id}；创建用 POST /users；更新用 PUT /users/{id}；删除用 DELETE /users/{id}。' },

  // ============ 十、应用性能（黄山版新增）============
  { code: '10.1', level: 'MANDATORY', category: '应用性能',
    title: '关注应用性能，要看以下指标：响应时间、QPS、TPS、最大并发数、事务成功率、PV、UV',
    content: 'QPS（Queries Per Second）和 TPS（Transactions Per Second）是核心衡量指标。接口 RT（Response Time）一般要求 P99 < 500ms。' },
  { code: '10.2', level: 'MANDATORY', category: '应用性能',
    title: '应用性能问题出现时，关注 top 命令的 CPU 和内存、jstack 线程栈、GC 日志',
    content: '分析工具：jstat（GC）、jmap（heap dump）、jstack（thread dump）、arthas（在线诊断）。' },
  { code: '10.3', level: 'MANDATORY', category: '应用性能',
    title: '应用代码中的 Redis 命令避免使用 KEYS 命令',
    content: 'KEYS * 会阻塞 Redis，随着 key 数量的增加查询耗时线性增加。用 SCAN 增量遍历。' },
  { code: '10.4', level: 'MANDATORY', category: '应用性能',
    title: '合理利用缓存，可以在一定程度上提升查询性能',
    content: '但是要注意缓存失效可能带来的缓存穿透、缓存击穿、缓存雪崩。常见方案：空值缓存、互斥锁、随机过期时间、多级缓存。' },
  { code: '10.5', level: 'MANDATORY', category: '应用性能',
    title: '禁止在业务代码中写入 while 死循环，即便有 break 或 continue 分支',
    content: '用条件严谨的判断替代死循环，避免 CPU 空转。定时任务也应设置最大重试次数。' },
  { code: '10.6', level: 'RECOMMENDED', category: '应用性能',
    title: '避免在循环体内查询数据库',
    content: 'N+1 问题：批量查询一次加载，或用 IN 批量查询替代。',
    exampleBad: 'for (Long id : ids) {\n    User u = userMapper.selectById(id); // N 次查询\n}',
    exampleGood: 'List<User> users = userMapper.selectBatchIds(ids); // 1 次查询' },
  { code: '10.7', level: 'RECOMMENDED', category: '应用性能',
    title: '对于大数据量的循环批处理，建议使用 for 循环 + 分批处理，避免内存溢出',
    content: '每批处理 500 条左右，不要一次性加载到内存。' },
  { code: '10.8', level: 'RECOMMENDED', category: '应用性能',
    title: '应用接口调用 RPC 远程接口的主流程中，必须设置超时时间和最大重试次数',
    content: '不设置超时可能导致线程池打满、雪崩效应。推荐 Hystrix / Resilience4j。' },
  { code: '10.9', level: 'RECOMMENDED', category: '应用性能',
    title: '避免不必要的对象创建',
    content: '比如在 for 循环里 new 大对象、字符串 + 拼接（改 StringBuilder）、自动装箱。' },
  { code: '10.10', level: 'REFERENCE', category: '应用性能',
    title: '连接池的最大、最小连接数配置要科学合理',
    content: '数据库连接数 = ((核心数 * 2) + 有效磁盘数)；Redis 连接池按业务并发预估，不宜过大。' },

  // ============ 十一、研发效能（黄山版新增）============
  { code: '11.1', level: 'RECOMMENDED', category: '研发效能',
    title: '研发效能度量需要引入 DevOps 理念',
    content: '重点关注：部署频率、需求交付周期、服务恢复时间、变更失败率（DORA 四大指标）。' },
  { code: '11.2', level: 'RECOMMENDED', category: '研发效能',
    title: '代码仓库使用 Git 进行版本控制，合并请求必须经过 Code Review 后再合并',
    content: 'PR 描述清晰、单次提交文件不宜过多，便于评审。' },
  { code: '11.3', level: 'MANDATORY', category: '研发效能',
    title: '团队仓库必须有完整的自动化构建流程：编译、测试、打包、部署',
    content: '每次提交 PR 触发 CI；merge 到 main 触发 CD。失败立即通知相关人员。' },
  { code: '11.4', level: 'MANDATORY', category: '研发效能',
    title: '分支策略推荐 Git Flow 或 GitHub Flow',
    content: 'main 分支保护：不允许直接 push；feature 分支开发；develop 合并；release 发布；hotfix 紧急修复。' },
  { code: '11.5', level: 'RECOMMENDED', category: '研发效能',
    title: '提交 commit message 遵循规范',
    content: '推荐 Angular 规范：<type>(<scope>): <subject>。type 取 feat/fix/docs/style/refactor/test/chore 等。' },

  // ============ 十二、Spring 工程规约（黄山版强化）============
  { code: '12.1', level: 'MANDATORY', category: 'Spring 工程',
    title: '严禁使用 @Autowired 注解注入属性',
    content: '推荐基于构造器注入，如果必要使用 @Resource 注解。@Autowired 在字段注入时难以测试、容易 NPE。',
    exampleBad: '@Autowired\nprivate UserService userService;',
    exampleGood: '@RequiredArgsConstructor  // Lombok\npublic class XxxService {\n    private final UserService userService;\n}' },
  { code: '12.2', level: 'MANDATORY', category: 'Spring 工程',
    title: 'Bean 的命名使用 CamelCase 风格且使用名词',
    content: '特别注意：被 @Configuration 注解的类的成员变量必须是 static final 或使用 @Bean 声明的方法。' },
  { code: '12.3', level: 'MANDATORY', category: 'Spring 工程',
    title: 'Spring 容器中的 Bean 默认是单例的，因此线程安全问题要特别注意',
    content: '有状态的 Bean 必须使用 @Scope("prototype")；或使用 ThreadLocal 存放线程变量。' },
  { code: '12.4', level: 'MANDATORY', category: 'Spring 工程',
    title: 'Spring 事务传播属性使用默认的 REQUIRED',
    content: '一般场景用默认即可。REQUIRES_NEW 适用于独立业务场景。NEVER / NOT_SUPPORTED 极少使用。' },
  { code: '12.5', level: 'MANDATORY', category: 'Spring 工程',
    title: '@Transactional 注解应精确到方法，而不是类',
    content: '避免整个类的方法都走事务，浪费资源。只读方法加 @Transactional(readOnly = true)。' },
  { code: '12.6', level: 'MANDATORY', category: 'Spring 工程',
    title: '@Transactional 事务不要滥用。事务会影响数据库的 QPS',
    content: '使用事务的地方需考虑各方面的回滚方案，包括缓存回滚、搜索引擎回滚、消息补偿、统计修正等。' },
  { code: '12.7', level: 'MANDATORY', category: 'Spring 工程',
    title: '在 @Transactional 标注的方法中，方法内部调用自己的方法不会开启事务',
    content: '因为 Spring AOP 代理走不到内部调用。需要抽到另一个 Service，或者通过 ApplicationContext 拿自身代理。' },
  { code: '12.8', level: 'MANDATORY', category: 'Spring 工程',
    title: '高并发调用 RPC 服务时，不推荐使用 Hystrix',
    content: 'Hystrix 已停止维护。推荐 Resilience4j（本项目已用）或 Sentinel。配置熔断、限流、重试。' },
  { code: '12.9', level: 'RECOMMENDED', category: 'Spring 工程',
    title: '使用 RestTemplate / WebClient 替代原始 HttpURLConnection',
    content: 'WebClient 是 Spring 5 引入的响应式 HTTP 客户端，性能和 API 都更优。' },
  { code: '12.10', level: 'RECOMMENDED', category: 'Spring 工程',
    title: 'Controller 方法参数建议使用 POJO 封装',
    content: '多于 3 个参数必须用 DTO 封装；单个参数也可以用 POJO 以便后续扩展。' },
  { code: '12.11', level: 'MANDATORY', category: 'Spring 工程',
    title: 'Controller 层应该只做参数校验与简单编排，复杂业务逻辑放在 Service 层',
    content: 'Controller 不应含有业务规则；参数校验用 @Valid + JSR-303 注解。' },
  { code: '12.12', level: 'RECOMMENDED', category: 'Spring 工程',
    title: '避免使用 @EnableXXX 配置多个同类增强',
    content: '如 @EnableAsync 的 AsyncConfigurer 只能有一个，多配置会报错。' },

  // ============ 十三、其他（黄山版补充）============
  { code: '13.1', level: 'MANDATORY', category: '其他',
    title: '在使用正则表达式时，利用好其预编译功能，可以有效加快正则匹配速度',
    content: 'Pattern 对象不要在方法体内定义，每次调用都会重新 compile；应作为类变量预编译。',
    exampleBad: 'String s = Pattern.compile(REGEX).matcher(input).replaceAll("");',
    exampleGood: 'private static final Pattern P = Pattern.compile(REGEX);' },
  { code: '13.2', level: 'MANDATORY', category: '其他',
    title: 'velocity 调用 POJO 类的属性时，直接使用属性名取值即可',
    content: '模板引擎自动按规范调用 getXxx。布尔类型变量不加 is 前缀。' },
  { code: '13.3', level: 'MANDATORY', category: '其他',
    title: '后台输送给页面的变量必须加 $!{var}',
    content: '中间的感叹号防止 NPE。${var} 变量值为 null 时会输出字符串 "null"。' },
  { code: '13.4', level: 'MANDATORY', category: '其他',
    title: '注意 Math.random() 这个方法返回的是 double 类型',
    content: '注意范围 0.0 ≤ x < 1.0，要获取整数类型的随机数，不要将 x 放大 10 的若干倍然后取整，直接使用 Random 对象的 nextInt 或 nextLong 方法。' },
  { code: '13.5', level: 'MANDATORY', category: '其他',
    title: '获取当前毫秒数 System.currentTimeMillis()',
    content: '而不是 new Date().getTime()。如果想获取更加精确的纳秒级时间值，用 System.nanoTime() 方式。' },
  { code: '13.6', level: 'RECOMMENDED', category: '其他',
    title: '尽量不要在 vm 中加入变量声明、逻辑运算符、以及任何复杂的逻辑',
    content: '模板只做展示，业务逻辑放在 Controller / Service。' },
  { code: '13.7', level: 'RECOMMENDED', category: '其他',
    title: '任何数据结构的构造或初始化，都应指定大小，避免数据结构无限增长吃光内存',
    content: 'new ArrayList<>(expectedSize)、new HashMap<>(initCap)、new StringBuilder(cap)。' },
  { code: '13.8', level: 'RECOMMENDED', category: '其他',
    title: '及时清理不再使用的代码段或配置信息',
    content: '对于暂时被注释、以后可能重新使用的代码段，在注释上用 // TODO 标明预计恢复时间，便于人员轮换后进行清理。长时间（2 周）不使用的代码进行删除。' },
]

/** 用于规约库页面侧边栏：按类别分组的计数 */
export function computeCategoryStats() {
  const map = new Map<string, number>()
  rules.forEach(r => map.set(r.category, (map.get(r.category) || 0) + 1))
  return Array.from(map.entries()).map(([name, count]) => ({ name, count }))
}

/** 按大类聚合（用于左侧树形）*/
export function groupByTopCategory() {
  const groups = new Map<string, { name: string; children: Array<{ name: string; count: number }> }>()
  rules.forEach(r => {
    const [top, sub] = r.category.split('-')
    if (!groups.has(top)) groups.set(top, { name: top, children: [] })
    const g = groups.get(top)!
    const subName = sub || top
    const child = g.children.find(c => c.name === subName)
    if (child) child.count++
    else g.children.push({ name: subName, count: 1 })
  })
  return Array.from(groups.values())
}
